/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as BlankRouteRouteImport } from './routes/_blank/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as PublicProfileRouteImport } from './routes/_public/profile'
import { Route as HomeFloorRouteImport } from './routes/_home/floor'
import { Route as HomeBuildingsRouteImport } from './routes/_home/buildings'
import { Route as HomeBuilderRouteImport } from './routes/_home/builder'
import { Route as BlankAuthLoginRouteImport } from './routes/_blank/auth/login'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankRouteRoute = BlankRouteRouteImport.update({
  id: '/_blank',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicRouteRoute,
} as any)
const HomeFloorRoute = HomeFloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeBuildingsRoute = HomeBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeBuilderRoute = HomeBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => HomeRouteRoute,
} as any)
const BlankAuthLoginRoute = BlankAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => BlankRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/builder': typeof HomeBuilderRoute
  '/buildings': typeof HomeBuildingsRoute
  '/floor': typeof HomeFloorRoute
  '/profile': typeof PublicProfileRoute
  '/auth/login': typeof BlankAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/builder': typeof HomeBuilderRoute
  '/buildings': typeof HomeBuildingsRoute
  '/floor': typeof HomeFloorRoute
  '/profile': typeof PublicProfileRoute
  '/auth/login': typeof BlankAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_blank': typeof BlankRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_home/builder': typeof HomeBuilderRoute
  '/_home/buildings': typeof HomeBuildingsRoute
  '/_home/floor': typeof HomeFloorRoute
  '/_public/profile': typeof PublicProfileRoute
  '/_home/': typeof HomeIndexRoute
  '/_blank/auth/login': typeof BlankAuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/buildings'
    | '/floor'
    | '/profile'
    | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builder' | '/buildings' | '/floor' | '/profile' | '/auth/login'
  id:
    | '__root__'
    | '/_blank'
    | '/_home'
    | '/_public'
    | '/_home/builder'
    | '/_home/buildings'
    | '/_home/floor'
    | '/_public/profile'
    | '/_home/'
    | '/_blank/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BlankRouteRoute: typeof BlankRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blank': {
      id: '/_blank'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BlankRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_public/profile': {
      id: '/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_home/floor': {
      id: '/_home/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof HomeFloorRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/buildings': {
      id: '/_home/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof HomeBuildingsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/builder': {
      id: '/_home/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof HomeBuilderRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_blank/auth/login': {
      id: '/_blank/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof BlankAuthLoginRouteImport
      parentRoute: typeof BlankRouteRoute
    }
  }
}

interface BlankRouteRouteChildren {
  BlankAuthLoginRoute: typeof BlankAuthLoginRoute
}

const BlankRouteRouteChildren: BlankRouteRouteChildren = {
  BlankAuthLoginRoute: BlankAuthLoginRoute,
}

const BlankRouteRouteWithChildren = BlankRouteRoute._addFileChildren(
  BlankRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeBuilderRoute: typeof HomeBuilderRoute
  HomeBuildingsRoute: typeof HomeBuildingsRoute
  HomeFloorRoute: typeof HomeFloorRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeBuilderRoute: HomeBuilderRoute,
  HomeBuildingsRoute: HomeBuildingsRoute,
  HomeFloorRoute: HomeFloorRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicProfileRoute: typeof PublicProfileRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicProfileRoute: PublicProfileRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  BlankRouteRoute: BlankRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
